name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Deploy Code to EC2
    - name: Deploy to EC2
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_USER: ${{ secrets.AWS_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Save the private key to a file
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Ensure .ssh directory exists
        mkdir -p ~/.ssh

        # Add the EC2 instance to known_hosts
        ssh-keyscan -H $AWS_HOST >> ~/.ssh/known_hosts

        # SSH into the instance and execute deployment commands
        ssh -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
          set -e # Exit on any error
          cd /home/ubuntu/Moodify-server
          git fetch origin main
          git reset --hard origin/main
          pm2 restart all
        EOF

        # Clean up the private key
        rm -f private_key.pem
